export const MOVIES = 'MOVIES'
export const GENRES = 'GENRES'
export const SELECTED_MOVIE = 'SELECTED_MOVIE'
export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING'
export const NOT_FOUND = 'NOT_FOUND'